# Generated by Django 5.1.7 on 2025-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
