# Generated by Django 5.1.7 on 2025-03-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_description_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Mode',
            field=models.CharField(choices=[('N', 'Non-Veg'), ('V', 'Veg')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
